### Create a new passenger
# POST http://localhost:3001/passengers
POST https://nestjs-vercel-delta.vercel.app/passengers
Content-Type: application/json

{
  "name": "Whiskers",
  "email": "johndoe@gmail.com",
  "phone": "1234567890"
}

### Get all passengers
# GET http://localhost:3001/passengers
GET https://nestjs-vercel-delta.vercel.app/passengers
Content-Type: application/json